// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip.proto

package gsp_tcp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_Unknown     MsgType = 0
	MsgType_SubInit     MsgType = 1
	MsgType_Forward     MsgType = 2
	MsgType_VoteContact MsgType = 3
	MsgType_GotContact  MsgType = 4
	MsgType_HeartBeat   MsgType = 5
	MsgType_WelCome     MsgType = 6
	MsgType_UpdateIV    MsgType = 7
	MsgType_UpdateOV    MsgType = 8
	MsgType_ReplaceOV   MsgType = 9
	MsgType_RemoveOV    MsgType = 10
	MsgType_SubAck      MsgType = 21
)

var MsgType_name = map[int32]string{
	0:  "Unknown",
	1:  "SubInit",
	2:  "Forward",
	3:  "VoteContact",
	4:  "GotContact",
	5:  "HeartBeat",
	6:  "WelCome",
	7:  "UpdateIV",
	8:  "UpdateOV",
	9:  "ReplaceOV",
	10: "RemoveOV",
	21: "SubAck",
}

var MsgType_value = map[string]int32{
	"Unknown":     0,
	"SubInit":     1,
	"Forward":     2,
	"VoteContact": 3,
	"GotContact":  4,
	"HeartBeat":   5,
	"WelCome":     6,
	"UpdateIV":    7,
	"UpdateOV":    8,
	"ReplaceOV":   9,
	"RemoveOV":    10,
	"SubAck":      21,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{0}
}

type Subscribe struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	IsReSub              bool     `protobuf:"varint,2,opt,name=isReSub,proto3" json:"isReSub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}
func (*Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{0}
}

func (m *Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscribe.Unmarshal(m, b)
}
func (m *Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscribe.Marshal(b, m, deterministic)
}
func (m *Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscribe.Merge(m, src)
}
func (m *Subscribe) XXX_Size() int {
	return xxx_messageInfo_Subscribe.Size(m)
}
func (m *Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Subscribe proto.InternalMessageInfo

func (m *Subscribe) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Subscribe) GetIsReSub() bool {
	if m != nil {
		return m.IsReSub
	}
	return false
}

type Vote struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	TTL                  int32    `protobuf:"varint,3,opt,name=TTL,proto3" json:"TTL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{1}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Vote) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Vote) GetTTL() int32 {
	if m != nil {
		return m.TTL
	}
	return 0
}

type ID struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type IDWithIP struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDWithIP) Reset()         { *m = IDWithIP{} }
func (m *IDWithIP) String() string { return proto.CompactTextString(m) }
func (*IDWithIP) ProtoMessage()    {}
func (*IDWithIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{3}
}

func (m *IDWithIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDWithIP.Unmarshal(m, b)
}
func (m *IDWithIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDWithIP.Marshal(b, m, deterministic)
}
func (m *IDWithIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDWithIP.Merge(m, src)
}
func (m *IDWithIP) XXX_Size() int {
	return xxx_messageInfo_IDWithIP.Size(m)
}
func (m *IDWithIP) XXX_DiscardUnknown() {
	xxx_messageInfo_IDWithIP.DiscardUnknown(m)
}

var xxx_messageInfo_IDWithIP proto.InternalMessageInfo

func (m *IDWithIP) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *IDWithIP) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type ForwardMsg struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardMsg) Reset()         { *m = ForwardMsg{} }
func (m *ForwardMsg) String() string { return proto.CompactTextString(m) }
func (*ForwardMsg) ProtoMessage()    {}
func (*ForwardMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{4}
}

func (m *ForwardMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardMsg.Unmarshal(m, b)
}
func (m *ForwardMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardMsg.Marshal(b, m, deterministic)
}
func (m *ForwardMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardMsg.Merge(m, src)
}
func (m *ForwardMsg) XXX_Size() int {
	return xxx_messageInfo_ForwardMsg.Size(m)
}
func (m *ForwardMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardMsg proto.InternalMessageInfo

func (m *ForwardMsg) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ForwardMsg) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ForwardMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

type Weight struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Weight               float64  `protobuf:"fixed64,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weight) Reset()         { *m = Weight{} }
func (m *Weight) String() string { return proto.CompactTextString(m) }
func (*Weight) ProtoMessage()    {}
func (*Weight) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{5}
}

func (m *Weight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weight.Unmarshal(m, b)
}
func (m *Weight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weight.Marshal(b, m, deterministic)
}
func (m *Weight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weight.Merge(m, src)
}
func (m *Weight) XXX_Size() int {
	return xxx_messageInfo_Weight.Size(m)
}
func (m *Weight) XXX_DiscardUnknown() {
	xxx_messageInfo_Weight.DiscardUnknown(m)
}

var xxx_messageInfo_Weight proto.InternalMessageInfo

func (m *Weight) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Weight) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type CtrlMsg struct {
	Type                 MsgType     `protobuf:"varint,1,opt,name=Type,proto3,enum=gsp.tcp.MsgType" json:"Type,omitempty"`
	Subscribe            *Subscribe  `protobuf:"bytes,2,opt,name=Subscribe,proto3" json:"Subscribe,omitempty"`
	Vote                 *Vote       `protobuf:"bytes,3,opt,name=Vote,proto3" json:"Vote,omitempty"`
	Forward              *ForwardMsg `protobuf:"bytes,4,opt,name=Forward,proto3" json:"Forward,omitempty"`
	GotContact           *ID         `protobuf:"bytes,5,opt,name=GotContact,proto3" json:"GotContact,omitempty"`
	HeartBeat            *ID         `protobuf:"bytes,6,opt,name=HeartBeat,proto3" json:"HeartBeat,omitempty"`
	Welcome              *ID         `protobuf:"bytes,7,opt,name=Welcome,proto3" json:"Welcome,omitempty"`
	UpdateWeight         *Weight     `protobuf:"bytes,8,opt,name=UpdateWeight,proto3" json:"UpdateWeight,omitempty"`
	Replace              *IDWithIP   `protobuf:"bytes,9,opt,name=Replace,proto3" json:"Replace,omitempty"`
	Remove               *ID         `protobuf:"bytes,10,opt,name=Remove,proto3" json:"Remove,omitempty"`
	SubAck               *ID         `protobuf:"bytes,21,opt,name=SubAck,proto3" json:"SubAck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CtrlMsg) Reset()         { *m = CtrlMsg{} }
func (m *CtrlMsg) String() string { return proto.CompactTextString(m) }
func (*CtrlMsg) ProtoMessage()    {}
func (*CtrlMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{6}
}

func (m *CtrlMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtrlMsg.Unmarshal(m, b)
}
func (m *CtrlMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtrlMsg.Marshal(b, m, deterministic)
}
func (m *CtrlMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtrlMsg.Merge(m, src)
}
func (m *CtrlMsg) XXX_Size() int {
	return xxx_messageInfo_CtrlMsg.Size(m)
}
func (m *CtrlMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CtrlMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CtrlMsg proto.InternalMessageInfo

func (m *CtrlMsg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_Unknown
}

func (m *CtrlMsg) GetSubscribe() *Subscribe {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

func (m *CtrlMsg) GetVote() *Vote {
	if m != nil {
		return m.Vote
	}
	return nil
}

func (m *CtrlMsg) GetForward() *ForwardMsg {
	if m != nil {
		return m.Forward
	}
	return nil
}

func (m *CtrlMsg) GetGotContact() *ID {
	if m != nil {
		return m.GotContact
	}
	return nil
}

func (m *CtrlMsg) GetHeartBeat() *ID {
	if m != nil {
		return m.HeartBeat
	}
	return nil
}

func (m *CtrlMsg) GetWelcome() *ID {
	if m != nil {
		return m.Welcome
	}
	return nil
}

func (m *CtrlMsg) GetUpdateWeight() *Weight {
	if m != nil {
		return m.UpdateWeight
	}
	return nil
}

func (m *CtrlMsg) GetReplace() *IDWithIP {
	if m != nil {
		return m.Replace
	}
	return nil
}

func (m *CtrlMsg) GetRemove() *ID {
	if m != nil {
		return m.Remove
	}
	return nil
}

func (m *CtrlMsg) GetSubAck() *ID {
	if m != nil {
		return m.SubAck
	}
	return nil
}

func init() {
	proto.RegisterEnum("gsp.tcp.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Subscribe)(nil), "gsp.tcp.Subscribe")
	proto.RegisterType((*Vote)(nil), "gsp.tcp.Vote")
	proto.RegisterType((*ID)(nil), "gsp.tcp.ID")
	proto.RegisterType((*IDWithIP)(nil), "gsp.tcp.IDWithIP")
	proto.RegisterType((*ForwardMsg)(nil), "gsp.tcp.ForwardMsg")
	proto.RegisterType((*Weight)(nil), "gsp.tcp.Weight")
	proto.RegisterType((*CtrlMsg)(nil), "gsp.tcp.CtrlMsg")
}

func init() { proto.RegisterFile("gossip.proto", fileDescriptor_878fa4887b90140c) }

var fileDescriptor_878fa4887b90140c = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x18, 0xc5, 0x49, 0xff, 0x24, 0xcd, 0xd7, 0xad, 0x33, 0x86, 0x4d, 0xbe, 0xe0, 0xa2, 0x04, 0x90,
	0x0a, 0x13, 0x15, 0xea, 0x6e, 0xb8, 0x41, 0x02, 0x5a, 0x01, 0x46, 0x8c, 0x56, 0x6e, 0xd7, 0x5e,
	0x27, 0xa9, 0x95, 0x45, 0x6b, 0xe3, 0x28, 0x71, 0x99, 0x78, 0x2d, 0x1e, 0x88, 0x67, 0x41, 0x76,
	0x9c, 0x34, 0x53, 0x99, 0xb4, 0xbb, 0x1e, 0x9f, 0xdf, 0x71, 0x3f, 0x9f, 0xaf, 0x85, 0xa3, 0x48,
	0xe4, 0x79, 0x9c, 0x0e, 0xd3, 0x4c, 0x48, 0x81, 0x9d, 0x28, 0x4f, 0x87, 0x32, 0x4c, 0xbd, 0x0f,
	0xe0, 0xce, 0x77, 0x41, 0x1e, 0x66, 0x71, 0xc0, 0xf1, 0x19, 0xd8, 0x3f, 0xc5, 0x9a, 0xd3, 0x35,
	0xb1, 0xfa, 0xd6, 0xc0, 0x65, 0x46, 0x61, 0x02, 0x4e, 0x9c, 0x33, 0x3e, 0xdf, 0x05, 0xa4, 0xd1,
	0xb7, 0x06, 0x1d, 0x56, 0x4a, 0xef, 0x23, 0xb4, 0x96, 0x42, 0xde, 0x9f, 0xec, 0x41, 0x83, 0xce,
	0x74, 0xc8, 0x65, 0x0d, 0x3a, 0xc3, 0x08, 0x9a, 0x8b, 0xc5, 0x0f, 0xd2, 0xec, 0x5b, 0x83, 0x36,
	0x53, 0x1f, 0xbd, 0x67, 0xd0, 0xa0, 0x13, 0x95, 0x4f, 0xee, 0xe4, 0x0b, 0xe5, 0x8d, 0xa0, 0x43,
	0x27, 0xab, 0x58, 0x5e, 0xd3, 0xd9, 0x43, 0xbf, 0xc3, 0xfb, 0x0e, 0xf0, 0x45, 0x64, 0xb7, 0x7e,
	0xb6, 0xbe, 0xcc, 0xa3, 0x07, 0x4f, 0xf6, 0x14, 0xda, 0xdb, 0x3c, 0xa2, 0x6b, 0x3d, 0x9b, 0xcb,
	0x0a, 0xe1, 0xbd, 0x07, 0x7b, 0xc5, 0xe3, 0xe8, 0x5a, 0xde, 0x7b, 0xcf, 0x59, 0x49, 0xe8, 0xbb,
	0x2c, 0x66, 0x94, 0xf7, 0xb7, 0x09, 0xce, 0x58, 0x66, 0x1b, 0x35, 0xc3, 0x4b, 0x68, 0x2d, 0x7e,
	0xa7, 0x5c, 0x27, 0x7b, 0x23, 0x34, 0x34, 0xe5, 0x0f, 0x2f, 0xf3, 0x48, 0x9d, 0x33, 0xed, 0xe2,
	0x77, 0xb5, 0x55, 0xe8, 0xcb, 0xba, 0x23, 0x5c, 0xa1, 0x95, 0xc3, 0x6a, 0xfb, 0x7a, 0x5e, 0xb4,
	0xaf, 0x47, 0xee, 0x8e, 0x8e, 0x2b, 0x58, 0x1d, 0xb2, 0x62, 0x31, 0x6f, 0xc1, 0x31, 0x65, 0x90,
	0x96, 0xa6, 0x9e, 0x54, 0xd4, 0xbe, 0x24, 0x56, 0x32, 0xf8, 0x1c, 0xe0, 0xab, 0x90, 0x63, 0x91,
	0x48, 0x3f, 0x94, 0xa4, 0xad, 0x13, 0xdd, 0x2a, 0x41, 0x27, 0xac, 0x66, 0xe3, 0xd7, 0xe0, 0x7e,
	0xe3, 0x7e, 0x26, 0x3f, 0x73, 0x5f, 0x12, 0xfb, 0x90, 0xdd, 0xbb, 0xf8, 0x15, 0x38, 0x2b, 0xbe,
	0x09, 0xc5, 0x96, 0x13, 0xe7, 0x10, 0x2c, 0x3d, 0x7c, 0x01, 0x47, 0x57, 0xe9, 0xda, 0x97, 0xdc,
	0x54, 0xda, 0xd1, 0xec, 0x49, 0xc5, 0x16, 0xc7, 0xec, 0x0e, 0x84, 0xcf, 0xc1, 0x61, 0x3c, 0xdd,
	0xf8, 0x21, 0x27, 0xae, 0xe6, 0x1f, 0xd7, 0xee, 0x2e, 0x7e, 0x3b, 0xac, 0x24, 0xf0, 0x0b, 0xb0,
	0x19, 0xdf, 0x8a, 0x5f, 0x9c, 0xc0, 0xe1, 0x1c, 0xc6, 0x52, 0xd0, 0x7c, 0x17, 0x7c, 0x0a, 0x6f,
	0xc8, 0xe9, 0x7f, 0xa0, 0xc2, 0x7a, 0xf3, 0xc7, 0x02, 0xc7, 0x2c, 0x10, 0x77, 0xc1, 0xb9, 0x4a,
	0x6e, 0x12, 0x71, 0x9b, 0xa0, 0x47, 0x4a, 0xcc, 0x77, 0x01, 0x4d, 0x62, 0x89, 0x2c, 0x25, 0x4c,
	0xb7, 0xa8, 0x81, 0x4f, 0xa0, 0xab, 0x96, 0x62, 0xfa, 0x43, 0x4d, 0xdc, 0xab, 0xd7, 0x8d, 0x5a,
	0xf8, 0xb8, 0xd6, 0x28, 0x6a, 0xab, 0xf0, 0x8a, 0x6f, 0xc6, 0x62, 0xcb, 0x91, 0x8d, 0x8f, 0xa0,
	0x53, 0x3c, 0x9b, 0x2e, 0x91, 0xb3, 0x57, 0xd3, 0x25, 0xea, 0xa8, 0x9c, 0x79, 0xe0, 0x74, 0x89,
	0x5c, 0x65, 0x16, 0x2f, 0x99, 0x2e, 0x11, 0x60, 0x28, 0x5f, 0x83, 0x4e, 0x03, 0x5b, 0xff, 0xfd,
	0x2f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x3f, 0x85, 0x31, 0x0e, 0x04, 0x00, 0x00,
}
